skip_frontmatter: true

linters:
  HtmlAttributes:
    exclude:
      - "source/layouts/base.haml"

  IdNames:
    exclude:
      - "source/guides/bundler_plugins.html.haml"
      - "source/guides/bundler_workflow.html.haml"
      - "source/guides/rails.html.haml"
      - "source/v1.15/guides/rails.html.haml"

  # Exlcude some files to align with ronn-generated HTML
  # see https://github.com/rubygems/bundler-site/pull/860
  IdNames:
    exclude:
      - "source/v2.1/bundle_plugin.html.haml"
      - "source/v2.2/bundle_plugin.html.haml"
      - "source/v2.3/bundle_plugin.html.haml"

  InlineStyles:
    exclude:
      - "source/contributors.html.haml"
      - "source/layouts/_navbar.haml"

  LineLength:
    max: 849

  RepeatedId:
    exclude:
      - "source/guides/bundler_plugins.html.haml"

  RuboCop:
    enabled: true
    ignored_cops:
      - "Style/StringLiterals"

  SpaceBeforeScript:
    exclude:
      - "source/v1.13/whats_new.html.haml"
      - "source/v1.14/whats_new.html.haml"
      - "source/v1.15/whats_new.html.haml"
      - "source/v1.16/whats_new.html.haml"
      - "source/v1.17/whats_new.html.haml"
      - "source/v2.0/whats_new.html.haml"
      - "source/v2.1/whats_new.html.haml"
      - "source/v2.2/whats_new.html.haml"
      - "source/v2.3/whats_new.html.haml"

  SpaceInsideHashAttributes:
    exclude:
      - "source/contributors.html.haml"
      - "source/layouts/_favicon.haml"
      - "source/layouts/_navbar.haml"
      - "source/layouts/base.haml"
      - "source/partials/_commands_sidebar.haml"
      - "source/partials/_guides_sidebar.haml"

  TagName:
    exclude:
      - "source/contributors.html.haml"

  UnnecessaryStringOutput:
    exclude:
      - "source/layouts/base.haml"
      - "source/v1.13/whats_new.html.haml"
      - "source/v1.14/whats_new.html.haml"
      - "source/v1.15/whats_new.html.haml"
      - "source/v1.16/whats_new.html.haml"
      - "source/v1.17/whats_new.html.haml"
      - "source/v2.0/whats_new.html.haml"
      - "source/v2.1/whats_new.html.haml"
      - "source/v2.2/whats_new.html.haml"
      - "source/v2.3/whats_new.html.haml"

  ViewLength:
    max: 413
