AllCops:
  DisabledByDefault: true

Bundler/OrderedGems:
  Enabled: true

# Unsupported by haml-lint https://github.com/sds/haml-lint/issues/333
Layout/ArgumentAlignment:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
