AllCops:
  DisabledByDefault: true

Bundler/OrderedGems:
  Enabled: true

Layout/ArgumentAlignment:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
