source 'https://rubygems.org'
ruby '2.3.1'

gem 'middleman', '~> 4.1'
gem 'middleman-livereload'
gem 'middleman-syntax', github: 'middleman/middleman-syntax'
gem 'middleman-blog'
gem 'middleman-compass'
gem 'rake'
gem 'ronn'
gem 'kramdown'
gem 'builder'
