source 'https://rubygems.org'
ruby '2.3.1'

gem 'octokit', '~> 4.3'
gem 'middleman', '~> 4.1'
gem 'middleman-livereload'
gem 'middleman-syntax', github: 'middleman/middleman-syntax'
gem 'middleman-blog'
gem 'middleman-compass'
gem 'middleman-minify-html'
gem 'puma', '~> 3.4'
gem 'middleman-sprockets', '~> 4.0'
gem 'middleman-search'
gem 'rake'
gem 'ronn'
gem 'kramdown'
gem 'builder'
gem 'bootstrap-sass'
gem 'jquery-middleman'
gem 'nokogiri'

group :development do
  gem 'pry'
  gem 'pry-byebug'
end
